volumes:
  db-data-mysql:

services:
  mlivro-mysql:
    image: "mysql:8.4"
    volumes:
      - db-data-mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mlivro_db
      MYSQL_USER: mlivro_user
      MYSQL_PASSWORD: mlivro_password
      MYSQL_ROOT_PASSWORD: root_password_segura
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 400M